<a href="https://colab.research.google.com/github/saichaitanyareddyb2025-sketch/EDA/blob/main/EXP4_28.07.2026/Missing%20Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Handling Missing Data - Filling Strategies

In [26]:
import pandas as pd
import numpy as np
from IPython.display import display # Import display function

# Recreate the initial DataFrame with missing values as described in the context
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])

# Add missing values
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx.loc['apple', 'store4'] = 20.0 # Fix for ChainedAssignmentError warning

print("Original DataFrame with NaNs:")
display(dfx)

Original DataFrame with NaNs:

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

### Strategy 1: Filling with a constant value

In [27]:
# Fill all NaN values with a constant (e.g., 0) using .replace() for a different approach
# Note: While df.fillna(0) is common, df.replace(np.nan, 0) also achieves the same for NaNs.
filled_df_replace = dfx.replace(np.nan, 0)
print("DataFrame after filling NaNs with 0 using .replace():")
display(filled_df_replace)

# Compare means to the original dfx to see the impact of filling
print("Mean of original dfx:\n", dfx.mean())
print("Mean of filled_df_replace:\n", filled_df_replace.mean())

DataFrame after filling NaNs with 0 using .replace():

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

Mean of original dfx:
 store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64
Mean of filled_df_replace:
 store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

### Strategy 2: Forward and Backward Filling

In [28]:
# Forward-fill (ffill) the 'store4' column
ffilled_store4 = dfx['store4'].ffill()
print("Forward-filled 'store4' column:")
display(ffilled_store4)

# Backward-fill (bfill) the 'store4' column
bf_filled_store4 = dfx['store4'].bfill()
print("Backward-filled 'store4' column:")
display(bf_filled_store4)

Forward-filled 'store4' column:

apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64

Backward-filled 'store4' column:

apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

### Strategy 3: Filling with statistical measures (e.g., mean, median)

In [29]:
# Fill missing values in 'store5' with its mean
# Note: This is an alternative to filling with a constant 0, often used for numerical data.

# Calculate the mean of 'store5' excluding NaNs
mean_store5 = dfx['store5'].mean()

# Fill NaNs in 'store5' with its mean
dfx_filled_mean = dfx.copy() # Work on a copy to avoid modifying original dfx
dfx_filled_mean['store5'] = dfx_filled_mean['store5'].fillna(mean_store5)

print(f"DataFrame after filling 'store5' NaNs with its mean ({mean_store5:.2f}):")
display(dfx_filled_mean)

# Fill all numerical columns with their respective means
dfx_filled_all_means = dfx.fillna(dfx.mean(numeric_only=True))
print("DataFrame after filling all numerical NaNs with column means:")
display(dfx_filled_all_means)

DataFrame after filling 'store5' NaNs with its mean (nan):

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

DataFrame after filling all numerical NaNs with column means:

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0    19.0     NaN
kiwi          21.0    22.0    23.0    19.0     NaN
grapes        24.0    25.0    26.0    19.0     NaN
mango         27.0    28.0    29.0    19.0     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges       20.0    21.0    22.0    19.0     NaN